# Generated by Django 5.1.4 on 2025-03-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jacket",
            name="jacket_type",
            field=models.CharField(
                choices=[
                    ("Off-Road", "Off-Road"),
                    ("Racing", "Racing"),
                    ("Adventure", "Adventure"),
                    ("Winter", "Winter"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="jacket",
            name="material",
            field=models.CharField(
                choices=[
                    ("Leather", "Leather"),
                    ("Textile", "Textile"),
                    ("Mesh", "Mesh"),
                ],
                max_length=100,
            ),
        ),
    ]
