# Generated by Django 5.1.4 on 2025-03-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0002_alter_jacket_jacket_type_alter_jacket_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jacket",
            name="pockets",
        ),
        migrations.RemoveField(
            model_name="jacket",
            name="thermal_liner",
        ),
    ]
