# Generated by Django 5.1.4 on 2025-03-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0004_remove_ridingpants_pockets_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminModel",
            fields=[
                (
                    "adminEmailId",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("adminPassword", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("FirstName", models.CharField(max_length=100)),
                ("LastName", models.CharField(max_length=100)),
                (
                    "EmailId",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("PhoneNo", models.CharField(max_length=100, unique=True)),
                ("Password", models.CharField(max_length=100)),
                ("DOB", models.CharField(max_length=100)),
                ("Gender", models.CharField(max_length=100)),
                ("StreetAddress", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=100)),
                ("State", models.CharField(max_length=100)),
                ("Country", models.CharField(max_length=100)),
                ("PinCode", models.CharField(max_length=100)),
            ],
        ),
    ]
