# Generated by Django 5.1.4 on 2025-03-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0006_faqmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminmodel",
            name="adminName",
            field=models.CharField(default=25, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminmodel",
            name="adminPhoneno",
            field=models.CharField(default=25, max_length=20),
            preserve_default=False,
        ),
    ]
