# Generated by Django 5.1.4 on 2025-03-22 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0011_remove_order_total_price_cart_cart_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cart_price",
        ),
    ]
