# Generated by Django 5.1.4 on 2025-03-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0016_order_city_order_country_order_pincode_order_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("payment_id", models.CharField(max_length=100, unique=True)),
                ("total_bill", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(default="Completed", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.usermodel",
                    ),
                ),
            ],
        ),
    ]
