# Generated by Django 5.1.4 on 2025-03-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0018_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart_items",
        ),
    ]
