# Generated by Django 5.2 on 2025-04-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0019_remove_order_cart_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="forgetpassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.IntegerField(unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.usermodel",
                    ),
                ),
                (
                    "user_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.adminmodel",
                    ),
                ),
            ],
        ),
    ]
