# Generated by Django 5.1.6 on 2025-04-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0021_alter_forgetpassword_otp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boots",
            old_name="boots_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="gloves",
            old_name="gloves_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="helmet",
            old_name="helmet_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="jacket",
            old_name="jacket_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="ridingpants",
            old_name="pants_type",
            new_name="type",
        ),
    ]
