# Generated by Django 5.1.4 on 2025-03-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_availability",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "boots_type",
                    models.CharField(
                        choices=[
                            ("Touring", "Touring"),
                            ("Racing", "Racing"),
                            ("Adventure", "Adventure"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("material", models.CharField(max_length=100)),
                ("certifications", models.CharField(max_length=50)),
                (
                    "closure_type",
                    models.CharField(
                        choices=[
                            ("Velcro", "Velcro"),
                            ("Zipper", "Zipper"),
                            ("Lace-up", "Lace-up"),
                        ],
                        max_length=50,
                    ),
                ),
                ("waterproofing", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gloves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_availability",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "gloves_type",
                    models.CharField(
                        choices=[
                            ("Full Gauntlet", "Full Gauntlet"),
                            ("Short Cuff", "Short Cuff"),
                            ("Winter", "Winter"),
                            ("Racing", "Racing"),
                            ("Adventure", "Adventure"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("material", models.CharField(max_length=100)),
                ("certifications", models.CharField(max_length=50)),
                ("waterproofing", models.BooleanField(default=False)),
                ("touchscreen_compatibility", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Helmet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_availability",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "helmet_type",
                    models.CharField(
                        choices=[
                            ("Full Face", "Full Face"),
                            ("Open Face", "Open Face"),
                            ("Modular", "Modular"),
                            ("Off-Road", "Off-Road"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "certifications",
                    models.CharField(
                        choices=[("DOT", "DOT"), ("ECE", "ECE"), ("ISI", "ISI")],
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Jacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_availability",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "jacket_type",
                    models.CharField(
                        choices=[
                            ("Textile", "Textile"),
                            ("Leather", "Leather"),
                            ("Mesh", "Mesh"),
                            ("Adventure", "Adventure"),
                            ("Winter", "Winter"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("material", models.CharField(max_length=100)),
                ("certifications", models.CharField(max_length=50)),
                ("reflective_elements", models.BooleanField(default=False)),
                (
                    "ventilation_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "padding_protection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("waterproofing", models.BooleanField(default=False)),
                ("thermal_liner", models.BooleanField(default=False)),
                ("pockets", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Kneeguard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_availability",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "protection_level",
                    models.CharField(
                        choices=[
                            ("CE Level 1", "CE Level 1"),
                            ("CE Level 2", "CE Level 2"),
                        ],
                        max_length=50,
                    ),
                ),
                ("adjustable_straps", models.BooleanField(default=False)),
                ("material", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RidingPants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_availability",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "pants_type",
                    models.CharField(
                        choices=[
                            ("Textile", "Textile"),
                            ("Leather", "Leather"),
                            ("Mesh", "Mesh"),
                            ("Adventure", "Adventure"),
                            ("Winter", "Winter"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("material", models.CharField(max_length=100)),
                ("certifications", models.CharField(max_length=50)),
                ("reflective_elements", models.BooleanField(default=False)),
                (
                    "ventilation_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "padding_protection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("waterproofing", models.BooleanField(default=False)),
                ("thermal_liner", models.BooleanField(default=False)),
                ("pockets", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
