# Generated by Django 5.1.4 on 2025-03-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0003_remove_jacket_pockets_remove_jacket_thermal_liner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ridingpants",
            name="pockets",
        ),
        migrations.RemoveField(
            model_name="ridingpants",
            name="thermal_liner",
        ),
        migrations.AlterField(
            model_name="ridingpants",
            name="material",
            field=models.CharField(
                choices=[
                    ("Leather", "Leather"),
                    ("Textile", "Textile"),
                    ("Mesh", "Mesh"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ridingpants",
            name="pants_type",
            field=models.CharField(
                choices=[
                    ("Off-Road", "Off-Road"),
                    ("Racing", "Racing"),
                    ("Adventure", "Adventure"),
                    ("Winter", "Winter"),
                ],
                max_length=50,
            ),
        ),
    ]
