# Generated by Django 5.1.4 on 2025-03-18 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0005_adminmodel_usermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("ans", models.CharField(max_length=500)),
                (
                    "emailId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.usermodel",
                    ),
                ),
            ],
        ),
    ]
