# Generated by Django 5.1.4 on 2025-03-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0007_adminmodel_adminname_adminmodel_adminphoneno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helmet",
            name="certifications",
            field=models.CharField(
                choices=[
                    ("DOT", "DOT"),
                    ("ECE", "ECE"),
                    ("ISI", "ISI"),
                    ("DOT,ECE", "DOT,ECE"),
                    ("DOT,ISI", "DOT,ISI"),
                    ("DOT,ECE,ISI", "DOT,ECE,ISI"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boots",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.boots",
                    ),
                ),
                (
                    "gloves",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.gloves",
                    ),
                ),
                (
                    "helmet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.helmet",
                    ),
                ),
                (
                    "jacket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.jacket",
                    ),
                ),
                (
                    "kneeguard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.kneeguard",
                    ),
                ),
                (
                    "ridingPants",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.ridingpants",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RevApp.usermodel",
                    ),
                ),
            ],
        ),
    ]
