# Generated by Django 5.1.4 on 2025-03-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0010_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_price",
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
            preserve_default=False,
        ),
    ]
