# Generated by Django 5.1.4 on 2025-03-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0012_remove_cart_cart_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="TotalBill",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="order",
            name="orderNo",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
