# Generated by Django 5.1.4 on 2025-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0013_order_totalbill_order_orderno"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
