# Generated by Django 5.1.4 on 2025-03-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0014_alter_order_options_order_payment_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
    ]
