# Generated by Django 5.1.4 on 2025-03-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0015_remove_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="City",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="Country",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="PinCode",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="State",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="StreetAddress",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
