# Generated by Django 5.2 on 2025-04-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RevApp", "0020_forgetpassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgetpassword",
            name="otp",
            field=models.IntegerField(),
        ),
    ]
